import type { Metadata } from "next";
import localFont from '@next/font/local'
import "./globals.css";

export const metadata: Metadata = {
  title: "Fabien Giraudier - Portfolio",
  description: "Generated by create next app",
};

const apfel = localFont({
  src: [
    {
      path: '../../public/fonts/ApfelGrotezk-Regular.otf',
      weight: '300'
    },
    {
      path: '../../public/fonts/ApfelGrotezk-Mittel.otf',
      weight: '500'
    },
    {
      path: '../../public/fonts/ApfelGrotezk-Fett.otf',
      weight: '700'
    },
    {
      path: '../../public/fonts/ApfelGrotezk-Satt.otf',
      weight: '900'
    },
  ],
  variable: '--font-apfel'
})

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={apfel.className}>{children}</body>
    </html>
  );
}
